-- begin WAREHOUSE_MATERIAL
alter table WAREHOUSE_MATERIAL add constraint FK_WAREHOUSE_MATERIAL_TYPE foreign key (TYPE_ID) references WAREHOUSE_TYPE(ID)^
alter table WAREHOUSE_MATERIAL add constraint FK_WAREHOUSE_MATERIAL_UNIT foreign key (UNIT_ID) references WAREHOUSE_UNIT(ID)^
create unique index IDX_WAREHOUSE_MATERIAL_UNIQ_MATERIAL_NUMBER on WAREHOUSE_MATERIAL (MATERIAL_NUMBER) ^
-- end WAREHOUSE_MATERIAL
-- begin WAREHOUSE_WAREHOUSE
create unique index IDX_WAREHOUSE_WAREHOUSE_UNIQ_WAREHOUSE_NUMBER on WAREHOUSE_WAREHOUSE (WAREHOUSE_NUMBER) ^
create unique index IDX_WAREHOUSE_WAREHOUSE_UNIQ_WAREHOUSE_NAME on WAREHOUSE_WAREHOUSE (WAREHOUSE_NAME) ^
-- end WAREHOUSE_WAREHOUSE
-- begin WAREHOUSE_STORE_POSTION
alter table WAREHOUSE_STORE_POSTION add constraint FK_WAREHOUSE_STORE_POSTION_WAREHOUSE foreign key (WAREHOUSE_ID) references WAREHOUSE_WAREHOUSE(ID)^
alter table WAREHOUSE_STORE_POSTION add constraint FK_WAREHOUSE_STORE_POSTION_MATERIAL foreign key (MATERIAL_ID) references WAREHOUSE_MATERIAL(ID)^
create unique index IDX_WAREHOUSE_STORE_POSTION_UNIQ_POSITION_NUMBER on WAREHOUSE_STORE_POSTION (POSITION_NUMBER) ^
-- end WAREHOUSE_STORE_POSTION

-- begin WAREHOUSE_SUPPLY
create unique index IDX_WAREHOUSE_SUPPLY_UNIQ_TELEPHONE on WAREHOUSE_SUPPLY (TELEPHONE) ^
-- end WAREHOUSE_SUPPLY
-- begin WAREHOUSE_STAFF
create unique index IDX_WAREHOUSE_STAFF_UNIQ_STAFF_NUMBER on WAREHOUSE_STAFF (STAFF_NUMBER) ^
create unique index IDX_WAREHOUSE_STAFF_UNIQ_CELL_PHONE on WAREHOUSE_STAFF (CELL_PHONE) ^
-- end WAREHOUSE_STAFF
-- begin WAREHOUSE_IN_STORE_ORDER
alter table WAREHOUSE_IN_STORE_ORDER add constraint FK_WAREHOUSE_IN_STORE_ORDER_SUPPLY foreign key (SUPPLY_ID) references WAREHOUSE_SUPPLY(ID)^
alter table WAREHOUSE_IN_STORE_ORDER add constraint FK_WAREHOUSE_IN_STORE_ORDER_STAFF foreign key (STAFF_ID) references WAREHOUSE_STAFF(ID)^
create unique index IDX_WAREHOUSE_IN_STORE_ORDER_UNIQ_IN_STORE_NUMBER on WAREHOUSE_IN_STORE_ORDER (IN_STORE_NUMBER) ^
-- end WAREHOUSE_IN_STORE_ORDER
-- begin WAREHOUSE_IN_ORDER_DETAIL
alter table WAREHOUSE_IN_ORDER_DETAIL add constraint FK_WAREHOUSE_IN_ORDER_DETAIL_MATERIAL foreign key (MATERIAL_ID) references WAREHOUSE_MATERIAL(ID)^
alter table WAREHOUSE_IN_ORDER_DETAIL add constraint FK_WAREHOUSE_IN_ORDER_DETAIL_STORE_POSITION foreign key (STORE_POSITION_ID) references WAREHOUSE_STORE_POSTION(ID)^
-- end WAREHOUSE_IN_ORDER_DETAIL
-- begin WAREHOUSE_OUT_STORE_ORDER
alter table WAREHOUSE_OUT_STORE_ORDER add constraint FK_WAREHOUSE_OUT_STORE_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references WAREHOUSE_CUSTOMER(ID)^
alter table WAREHOUSE_OUT_STORE_ORDER add constraint FK_WAREHOUSE_OUT_STORE_ORDER_STAFF foreign key (STAFF_ID) references WAREHOUSE_STAFF(ID)^
-- end WAREHOUSE_OUT_STORE_ORDER
-- begin WAREHOUSE_OUT_ORDER_DETAIL
alter table WAREHOUSE_OUT_ORDER_DETAIL add constraint FK_WAREHOUSE_OUT_ORDER_DETAIL_MATERIAL foreign key (MATERIAL_ID) references WAREHOUSE_MATERIAL(ID)^
-- end WAREHOUSE_OUT_ORDER_DETAIL
-- begin WAREHOUSE_IN_STORE_ORDER_IN_ORDER_DETAIL_LINK
alter table WAREHOUSE_IN_STORE_ORDER_IN_ORDER_DETAIL_LINK add constraint FK_WISOIODL_IN_STORE_ORDER foreign key (IN_STORE_ORDER_ID) references WAREHOUSE_IN_STORE_ORDER(ID)^
alter table WAREHOUSE_IN_STORE_ORDER_IN_ORDER_DETAIL_LINK add constraint FK_WISOIODL_IN_ORDER_DETAIL foreign key (IN_ORDER_DETAIL_ID) references WAREHOUSE_IN_ORDER_DETAIL(ID)^
-- end WAREHOUSE_IN_STORE_ORDER_IN_ORDER_DETAIL_LINK
-- begin WAREHOUSE_UNIT
create unique index IDX_WAREHOUSE_UNIT_UNIQ_NAME on WAREHOUSE_UNIT (NAME) ^
-- end WAREHOUSE_UNIT
-- begin WAREHOUSE_TYPE
create unique index IDX_WAREHOUSE_TYPE_UNIQ_NAME on WAREHOUSE_TYPE (NAME) ^
-- end WAREHOUSE_TYPE
-- begin WAREHOUSE_OUT_STORE_ORDER_OUT_ORDER_DETAIL_LINK
alter table WAREHOUSE_OUT_STORE_ORDER_OUT_ORDER_DETAIL_LINK add constraint FK_WOSOOODL_OUT_STORE_ORDER foreign key (OUT_STORE_ORDER_ID) references WAREHOUSE_OUT_STORE_ORDER(ID)^
alter table WAREHOUSE_OUT_STORE_ORDER_OUT_ORDER_DETAIL_LINK add constraint FK_WOSOOODL_OUT_ORDER_DETAIL foreign key (OUT_ORDER_DETAIL_ID) references WAREHOUSE_OUT_ORDER_DETAIL(ID)^
-- end WAREHOUSE_OUT_STORE_ORDER_OUT_ORDER_DETAIL_LINK
