alter table WAREHOUSE_OUT_STORE_ORDER add constraint FK_WAREHOUSE_OUT_STORE_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references WAREHOUSE_CUSTOMER(ID);
alter table WAREHOUSE_OUT_STORE_ORDER add constraint FK_WAREHOUSE_OUT_STORE_ORDER_STAFF foreign key (STAFF_ID) references WAREHOUSE_STAFF(ID);
