alter table WAREHOUSE_IN_STORE_ORDER add constraint FK_WAREHOUSE_IN_STORE_ORDER_SUPPLY foreign key (SUPPLY_ID) references WAREHOUSE_SUPPLY(ID);
alter table WAREHOUSE_IN_STORE_ORDER add constraint FK_WAREHOUSE_IN_STORE_ORDER_STAFF foreign key (STAFF_ID) references WAREHOUSE_STAFF(ID);
create unique index IDX_WAREHOUSE_IN_STORE_ORDER_UNIQ_IN_STORE_NUMBER on WAREHOUSE_IN_STORE_ORDER (IN_STORE_NUMBER) ;
