alter table WAREHOUSE_MATERIAL add constraint FK_WAREHOUSE_MATERIAL_TYPE foreign key (TYPE_ID) references WAREHOUSE_TYPE(ID);
alter table WAREHOUSE_MATERIAL add constraint FK_WAREHOUSE_MATERIAL_UNIT foreign key (UNIT_ID) references WAREHOUSE_UNIT(ID);
create unique index IDX_WAREHOUSE_MATERIAL_UNIQ_MATERIAL_NUMBER on WAREHOUSE_MATERIAL (MATERIAL_NUMBER) ;
