alter table WAREHOUSE_STORE_POSTION add constraint FK_WAREHOUSE_STORE_POSTION_WAREHOUSE foreign key (WAREHOUSE_ID) references WAREHOUSE_WAREHOUSE(ID);
alter table WAREHOUSE_STORE_POSTION add constraint FK_WAREHOUSE_STORE_POSTION_MATERIAL foreign key (MATERIAL_ID) references WAREHOUSE_MATERIAL(ID);
create unique index IDX_WAREHOUSE_STORE_POSTION_UNIQ_POSITION_NUMBER on WAREHOUSE_STORE_POSTION (POSITION_NUMBER) ;
