create unique index IDX_WAREHOUSE_WAREHOUSE_UNIQ_WAREHOUSE_NUMBER on WAREHOUSE_WAREHOUSE (WAREHOUSE_NUMBER) ;
create unique index IDX_WAREHOUSE_WAREHOUSE_UNIQ_WAREHOUSE_NAME on WAREHOUSE_WAREHOUSE (WAREHOUSE_NAME) ;
